export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOAD_PROFILE_REQUEST = "LOAD_PROFILE_REQUEST";
export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS";
export const LOAD_PROFILE_FAIL = "LOAD_PROFILE_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
export const FORGOT_PASSWORD_RESET = "FORGOT_PASSWORD_RESET";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_RESET = "RESET_PASSWORD_RESET";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const VERIFY_TASK_EXEC_REQUEST = "VERIFY_TASK_EXEC_REQUEST";
export const VERIFY_TASK_EXEC_SUCCESS = "VERIFY_TASK_EXEC_SUCCESS";
export const VERIFY_TASK_EXEC_RESET = "VERIFY_TASK_EXEC_RESET";
export const VERIFY_TASK_EXEC_FAIL = "VERIFY_TASK_EXEC_FAIL";

export const ACTIVATE_PACKAGE_REQUEST = "ACTIVATE_PACKAGE_REQUEST";
export const ACTIVATE_PACKAGE_RESET = "ACTIVATE_PACKAGE_RESET";
export const ACTIVATE_PACKAGE_SUCCESS = "ACTIVATE_PACKAGE_SUCCESS";
export const ACTIVATE_PACKAGE_FAIL = "ACTIVATE_PACKAGE_FAIL";

export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL";
export const CREATE_TASK_RESET = "CREATE_TASK_RESET";

export const UPDATE_BANK_INFO_REQUEST = "UPDATE_BANK_INFO_REQUEST";
export const UPDATE_BANK_INFO_SUCCESS = "UPDATE_BANK_INFO_SUCCESS";
export const UPDATE_BANK_INFO_FAIL = "UPDATE_BANK_INFO_FAIL";
export const UPDATE_BANK_INFO_RESET = "UPDATE_BANK_INFO_RESET";

export const GET_DAILY_TASK_REQUEST = "GET_DAILY_TASK_REQUEST";
export const GET_DAILY_TASK_SUCCESS = "GET_DAILY_TASK_SUCCESS";
export const GET_DAILY_TASK_FAIL = "GET_DAILY_TASK_FAIL";
export const GET_DAILY_TASK_RESET = "GET_DAILY_TASK_RESET";

export const GET_ACTIVE_TASK_PROGRESS_REQUEST =
  "GET_ACTIVE_TASK_PROGRESS_REQUEST";
export const GET_ACTIVE_TASK_PROGRESS_SUCCESS =
  "GET_ACTIVE_TASK_PROGRESS_SUCCESS";
export const GET_ACTIVE_TASK_PROGRESS_FAIL = "GET_ACTIVE_TASK_PROGRESS_FAIL";
export const GET_ACTIVE_TASK_PROGRESS_RESET = "GET_ACTIVE_TASK_PROGRESS_RESET";

export const GET_WALLET_REQUEST = "GET_WALLET_REQUEST";
export const GET_WALLET_SUCCESS = "GET_WALLET_SUCCESS";
export const GET_WALLET_FAIL = "GET_WALLET_FAIL";
export const GET_WALLET_RESET = "GET_WALLET_RESET";

export const LOG_OUT_USER_REQUEST = "LOG_OUT_USER_REQUEST";
export const LOG_OUT_USER_FAIL = "LOG_OUT_USER_FAIL ";
export const WITHDRAW_FUNDS_FAIL = "WITHDRAW_FUNDS_FAIL";
export const WITHDRAW_FUNDS_REQUEST = "WITHDRAW_FUNDS_REQUEST";
export const WITHDRAW_FUNDS_SUCCESS = "WITHDRAW_FUNDS_SUCCESS";
export const WITHDRAW_FUNDS_RESET = "WITHDRAW_FUNDS_RESET";

export const OTP_VERIFY_REQUEST = "OTP_VERIFY_REQUEST";
export const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS";
export const OTP_VERIFY_FAIL = "OTP_VERIFY_FAIL";
export const OTP_VERIFY_RESET = "OTP_VERIFY_RESET";

export const RESEND_OTP_REQUEST = "RESEND_OTP_REQUEST";
export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
export const RESEND_OTP_FAIL = "RESEND_OTP_FAIL";
export const RESEND_OTP_RESET = "RESEND_OTP_RESET";

export const GET_TX_HISTORY_REQUEST = "GET_TX_HISTORY_REQUEST";
export const GET_TX_HISTORY_SUCCESS = "GET_TX_HISTORY_SUCCESS";
export const GET_TX_HISTORY_RESET = "GET_TX_HISTORY_RESET";
export const GET_TX_HISTORY_FAIL = "GET_TX_HISTORY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
